---
title: "Hospital-Level Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(broom)
#inner-joined data of hosp_data and and hospital demographics data 
#each row is a unique physician, but there can be multiple physicians working in the same hospital
#nrow = 269663
hosp_merged <- readRDS("/Users/jiminyoo/Desktop/BST260-FALL2017/BST-260-Final-Project/Hosp_merged_data.rds")
```

#More Data Manipulation
#Aggregate hosp_merged data at hospital level so that each row is a unique hospital 
```{r}
full_data <- hosp_merged %>% 
  group_by(Hospital.affiliation.LBN.1, City_trimmed) 

#Recompute Gender and EHR-use variables into numerics
full_data$Gender_num <- ifelse(full_data$Gender == "F", 1, 0)
full_data$EHR_num <- ifelse(full_data$Used.electronic.health.records == "Y", 1, 0)

agg_data <- summarise(full_data, num_phys = n_distinct(NPI), female_prop = round(mean(Gender_num),2), avg_grad_year = mean(Graduation.year), n_specialty =n_distinct(Primary.specialty), EHR_use = max(EHR_num), staffed_beds = mean(Staffed_beds), total_discharge = mean(Total_discharges), patient_days = mean(Patient_days), gross_patient_rev = mean(Gross_patient_revenue))

table(agg_data$EHR_use)
# Checking the if the EHR_use variable is accurate
# EHR_y_list <- agg_data[agg_data$EHR_use == 1, ]$Hospital.affiliation.LBN.1
# EHR_y_data <- subset(hosp_merged, Hospital.affiliation.LBN.1 %in% EHR_y_list)
# table(EHR_y_data$Used.electronic.health.records)
# 
# EHR_n_hosp <- agg_data[agg_data$EHR_use == 0, ]
# test = inner_join(hosp_merged, EHR_n_hosp, by=c("Hospital.affiliation.LBN.1" = "Hospital.affiliation.LBN.1", "City_trimmed" = "City_trimmed"))
# table(test$Used.electronic.health.records)

#RECODE Using EHR_use==1 -> Y, 0 -> ""
agg_data$EHR_char <- ifelse(agg_data$EHR_use == 1, "Y", "Blank")
#RECODE Years since medical school graduation
agg_data$yrs_since_grad = 2017 - agg_data$avg_grad_year

table(agg_data$EHR_use)
which(is.na(agg_data$gross_patient_rev))
#data aggregated on hospital level
#each row is a uniquehospital 
#nrow = 1746
#setwd("~Desktop/BST260-FALL2017/BST-260-Final-Project")
#saveRDS(agg_data, "Hosps_aggregated.rds")
```
 
```{r}
#Explore small-sample size hospitals with less than ten physicians
lessTen <- agg_data[which(agg_data$num_phys < 10), ]
table(lessTen$EHR_char)
agg_data[agg_data$gross_patient_rev == 0, ]
```

#Exploratory Analysis: Box Plots
```{r}
boxplot(staffed_beds~EHR_char,data=agg_data, 
        xlab="EHR Use", ylab="Staffed_beds", ylim = c(0,1000))
boxplot(total_discharge~EHR_char,data=agg_data, 
        xlab="EHR Use", ylab="Total discharge")
boxplot(patient_days~EHR_char,data=agg_data, 
        xlab="EHR Use", ylab="Patient days")
boxplot(gross_patient_rev~EHR_char,data=agg_data, 
        xlab="EHR Use", ylab="Yearly gross patient revenue")
boxplot(num_phys~EHR_char ,data=agg_data, 
        xlab="EHR Use", ylab="Number of Practitioners")
boxplot(female_prop~EHR_char ,data=agg_data, 
        xlab="EHR Use", ylab="Proportion of Female")
boxplot(yrs_since_grad~EHR_char ,data=agg_data, 
        xlab="EHR Use", ylab="Years since graduation")
boxplot(n_specialty~EHR_char ,data=agg_data, 
        xlab="EHR Use", ylab="Number of specialties")
```

#Check for correlations
```{r}
#Load necesarry libraries 
library(RColorBrewer)
library(car)

#Check for correlations
X <- c("num_phys", "female_prop", "avg_grad_year", "n_specialty", "staffed_beds", "total_discharge", "patient_days", "gross_patient_rev")
cor(agg_data$num_phys, agg_data$EHR_use)
cor(agg_data$female_prop, agg_data$EHR_use)
cor(agg_data$yrs_since_grad, agg_data$EHR_use)
cor(agg_data$n_specialty, agg_data$EHR_use)
cor(agg_data$staffed_beds, agg_data$EHR_use)
cor(agg_data$total_discharge, agg_data$EHR_use)
cor(agg_data$patient_days, agg_data$EHR_use)
cor(agg_data$gross_patient_rev, agg_data$EHR_use)

#Correlation Matrix
my_colors <- brewer.pal(nlevels(as.factor(agg_data$EHR_char)), "Set1")
scatterplotMatrix(~num_phys+female_prop+yrs_since_grad+staffed_beds+gross_patient_rev|EHR_char, data=agg_data, col=my_colors , smoother.args=list(col="grey") , cex=1.5 , pch=c(15,16))


#Variables that are not normally distributed are logged: num_phys, staffed_bed, gross_patient_rev
agg_data$num_phys_log <- log(agg_data$num_phys)
agg_data$staffed_beds_log <- log(agg_data$staffed_beds)
agg_data$gross_patient_rev_log <- log(agg_data$gross_patient_rev)
agg_data$total_discharge_log <- log(agg_data$total_discharge)
agg_data$patient_days_log<- log(agg_data$patient_days)



#Noticeable correlations(more than 0.3): 
#EHR_use: EHR_use - num_phys_log, EHR_use-n_specialty, EHR_use-staffed_beds_log, EHR_use-gross_patient_rev_log
#Confounding (correlation over 0.7):
#num_phys_log-n_specialty/staffed_Bed _log/total_discharge/gross_patient_rev
#n_specialty-staffed_beds_log/ total_discharge/patient_days/gross_patient_rev_log
#staffed_bed_log-total_discharge, patient_days,gross_patient_rev_log
#total_discharge-patient_days, gross_patient_rev
#patient_days-gross_patient_rev_log
#Conclusion: Confounding factor is the size of the hospital that influences all number of physicians, number of specialties, number of staffed beds, total discharges, gross patient revenue
#Potential highest confounding factors are number of physicians-number of speciaties, staffed_beds - gross patient revenue, total discharge - patient days

agg_data_cor <- agg_data[, c("EHR_use", "num_phys_log","female_prop","n_specialty","staffed_beds_log","total_discharge","patient_days", "gross_patient_rev_log","yrs_since_grad")]
round(cor(agg_data_cor), 2)

#*Years since graduation comes out as NAs, so pull out yrs_since_grad correlation with only complete observations
round(cor(agg_data_cor, use="complete.obs"), 2)
#conclusion: weak negative correlation with all variables with all but female between -0.3 and 0. 
#strongest correlation is thefemale proportion, with is -0.44

#Correlation Matrix with logged variables
scatterplotMatrix(~num_phys_log+female_prop+yrs_since_grad+staffed_beds_log
                  +gross_patient_rev_log|EHR_char, data=agg_data, col=my_colors , smoother.args=list(col="grey") , cex=1.5 , pch=c(15,16))

```

```{r}
#How about stratified hospital sizes, and see EHR_use proportion?  
#Stratify with two most strongly correlated variables (number of physicians(corr=0.55), and gross_patient_rev_log(corr=0.45))
hist(agg_data$num_phys)
hist(agg_data$gross_patient_rev)

agg_data$num_phys_grp = cut(agg_data$num_phys, quantile(agg_data$num_phys, prob = seq(0, 1, .1)), include.lowest = TRUE)
agg_data$gpr_grp = cut(agg_data$gross_patient_rev, quantile(agg_data$gross_patient_rev, prob = seq(0, 1, .1)), include.lowest = TRUE)
#correlation between number of physicians and gross patientrevenue 
plot(agg_data$num_phys_log, agg_data$gross_patient_rev_log)

#Table: counts in num_phys and gpr groups
table(agg_data$num_phys_grp, agg_data$gpr_grp)
#Heatmap: num_phys, gross_patient_rev, EHR_use proportion
ggplot(data = agg_data, aes(x = num_phys_grp, y = gpr_grp)) +
  geom_tile(aes(fill = EHR_use)) 

filter_var = "patient_days"
agg_data %>%
    group_by(gpr_grp) %>%
    do(tidy(glm(EHR_use ~ num_phys + staffed_beds_log + total_discharge + patient_days, data = .))) %>%
    filter(term==filter_var)

#When stratified by gross patient revenue, NONE appears significant but NUMBER OF PHYSICIANS
res$estimate
```

#Making Models
```{r}
library(caret)
Train <- createDataPartition(agg_data$EHR_use, p=0.6, list=FALSE)
training <- agg_data[Train, ]
testing <- agg_data[-Train, ]

glm1 <- glm(EHR_use ~ gross_patient_rev_log + num_phys_log + staffed_beds_log + total_discharge_log + patient_days_log, data=training, family = "binomial")
summary(glm1)

#TEST GLM1 
p_hat_logit <- predict(glm1, newdata = testing, type="response")
y_hat_logit <- ifelse(p_hat_logit > 0.5, 1,  0)
confusionMatrix(data = y_hat_logit, reference = testing$EHR_use)

#TEST GLM2
glm2 <- glm(EHR_use ~ gross_patient_rev_log + num_phys_log + total_discharge_log , data=training, family = "binomial")
#TEST GLM2 

p_hat_logit <- predict(glm2, newdata = testing, type="response")
y_hat_logit <- ifelse(p_hat_logit > 0.5, 1,  0)
confusionMatrix(data = y_hat_logit, reference = testing$EHR_use)

anova(glm1, glm2, test ="Chisq")
#We should use GLm2 

#TEST GLM3
glm3 <- glm(EHR_use ~ gross_patient_rev_log + num_phys_log + gross_patient_rev_log*num_phys_log + total_discharge_log , data=training, family = "binomial")
summary(glm3)

p_hat_logit <- predict(glm3, newdata = testing, type="response")
y_hat_logit <- ifelse(p_hat_logit > 0.5, 1,  0)
confusionMatrix(data = y_hat_logit, reference = testing$EHR_use)
anova(glm2, glm3, test ="Chisq")

##*Write a funciton for confusionMatrix
```