---
title: "Maps"
output: html_document
---


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.




```{r}
library(fiftystater)
library(RColorBrewer)
library(tidyverse)
library(ggplot2)
data("fifty_states")
states_map <- map_data("state")

#mapplot <- dat_mu_ep %>% filter(agrepl("Cerner", Vendor_Name)) %>% group_by(Business_State_Territory) %>% summarize(count = n()) 
```

```{r}
age <- dat_merge %>% filter(!is.na(Graduation.year)) %>% group_by(Business_State_Territory) %>% summarize(yrsgrad = mean(2016 - Graduation.year))

age %>% 
  ggplot() +
  geom_map(aes(map_id = id), data = fifty_states, map = fifty_states, color="grey50", fill="grey90") +
  geom_map(aes(map_id = tolower(Business_State_Territory), fill = yrsgrad), map = fifty_states, color="grey50") +
  coord_map() +
  scale_fill_gradientn(colors = brewer.pal(6, "RdYlGn")) +
  expand_limits(x=states_map$long, y=states_map$lat) +
  theme_gray() +
  theme(axis.text = element_blank(), 
        axis.line = element_blank(), 
        axis.ticks = element_blank(), 
        panel.border = element_blank(), 
        panel.grid = element_blank(), 
        axis.title = element_blank(),
        legend.position = "bottom") +
  ggtitle("Years Since Graduation")

```

```{r}
dat_merge %>% 
  filter(!is.na(Graduation.year)) %>% 
  group_by(ZIP) %>% 
  summarize(yrsgrad = mean(2016 - Graduation.year)) %>% 
  ggplot() +
  geom_map(aes(map_id = id), data = fifty_states, map = fifty_states, color="grey50", fill="grey90") +
  geom_point(
        aes(x=longitude, y=latitude, show_guide = TRUE, colour=yrsgrad), 
        alpha=.8, size = 0.5, na.rm = T)  + 
  coord_map() +
  scale_fill_gradientn(colors = brewer.pal(6, "RdYlGn")) +
  expand_limits(x=states_map$long, y=states_map$lat) +
  theme_gray() +
  theme(axis.text = element_blank(), 
        axis.line = element_blank(), 
        axis.ticks = element_blank(), 
        panel.border = element_blank(), 
        panel.grid = element_blank(), 
        axis.title = element_blank(),
        legend.position = "bottom") +
  ggtitle("Years Since Graduation")
```

```{r}

# #this should have been 100%?
# useehr <- dat_merge %>% 
#   group_by(Business_State_Territory) %>% 
#   summarize(num = n(), used = sum(Used.electronic.health.records == "Y")) %>% 
#   mutate(pct = used/num)
# 
# useehr %>% 
#   ggplot() +
#   geom_map(aes(map_id = id), data = fifty_states, map = fifty_states, color="grey50", fill="grey90") +
#   geom_map(aes(map_id = tolower(Business_State_Territory), fill = pct), map = fifty_states, color="grey50") +
#   coord_map() +
#   scale_fill_gradientn(colors = brewer.pal(6, "RdYlGn")) +
#   expand_limits(x=states_map$long, y=states_map$lat) +
#   theme_gray() +
#   theme(axis.text = element_blank(), 
#         axis.line = element_blank(), 
#         axis.ticks = element_blank(), 
#         panel.border = element_blank(), 
#         panel.grid = element_blank(), 
#         axis.title = element_blank(),
#         legend.position = "bottom") +
#   ggtitle("Percent EHR Usage")
# 

useehr <- phys %>% 
  group_by(State) %>% 
  summarize(num = n(), used = sum(Used.electronic.health.records == "Y")) %>% 
  mutate(pct = used/num)

useehr %>% 
  ggplot() +
  geom_map(aes(map_id = id), data = fifty_states, map = fifty_states, color="grey50", fill="grey90") +
  geom_map(aes(map_id = tolower(State), fill = pct), map = fifty_states, color="grey50") +
  coord_map() +
  scale_fill_gradientn(colors = brewer.pal(6, "RdYlGn")) +
  expand_limits(x=states_map$long, y=states_map$lat) +
  theme_gray() +
  theme(axis.text = element_blank(), 
        axis.line = element_blank(), 
        axis.ticks = element_blank(), 
        panel.border = element_blank(), 
        panel.grid = element_blank(), 
        axis.title = element_blank(),
        legend.position = "bottom") +
  ggtitle("Percent EHR Usage")
```

```{r}
library(knitr)
library(gridExtra)
#levels(dat_merge$Product_Setting)
prod_setting <- dat_merge %>% 
  filter(!is.na(Product_Setting)) %>% 
  group_by(Business_State_Territory) %>% 
  summarize(num = n(), 
            amb = sum(Product_Setting == "Ambulatory"), 
            inpat = sum(Product_Setting == "Inpatient")) %>% 
  mutate(p_amb = amb/num, p_inpp = inpat/num)

# table for overall percentages in merge dataset
prod_setting_overall <- dat_merge %>% 
  summarize(total = n(), 
            amb = sum(Product_Setting == "Ambulatory"), 
            inpat = sum(Product_Setting == "Inpatient")) %>% 
  mutate("Ambulatory (Outpatient)" = amb/total, Inpatient= inpat/total) %>% 
  mutate(State = "Overall") %>% 
  select(State, "Ambulatory (Outpatient)", Inpatient)
prod_setting_overall %>% kable

ambulatory <- prod_setting %>% 
  ggplot() +
  geom_map(aes(map_id = id), data = fifty_states, map = fifty_states, color="grey50", fill="grey90") +
  geom_map(aes(map_id = tolower(Business_State_Territory), fill = p_amb), map = fifty_states, color="grey50") +
  coord_map() +
  scale_fill_gradientn(colors = brewer.pal(6, "RdYlGn")) +
  expand_limits(x=states_map$long, y=states_map$lat) +
  theme_gray() +
  theme(axis.text = element_blank(), 
        axis.line = element_blank(), 
        axis.ticks = element_blank(), 
        panel.border = element_blank(), 
        panel.grid = element_blank(), 
        axis.title = element_blank(),
        legend.position = "bottom") +
  ggtitle("Product Setting = Ambulatory")

inpatient <- prod_setting %>% 
  ggplot() +
  geom_map(aes(map_id = id), data = fifty_states, map = fifty_states, color="grey50", fill="grey90") +
  geom_map(aes(map_id = tolower(Business_State_Territory), fill = p_inpp), map = fifty_states, color="grey50") +
  coord_map() +
  scale_fill_gradientn(colors = brewer.pal(6, "RdYlGn")) +
  expand_limits(x=states_map$long, y=states_map$lat) +
  theme_gray() +
  theme(axis.text = element_blank(), 
        axis.line = element_blank(), 
        axis.ticks = element_blank(), 
        panel.border = element_blank(), 
        panel.grid = element_blank(), 
        axis.title = element_blank(),
        legend.position = "bottom") +
  ggtitle("Product Setting = Inpatient")

grid.arrange(ambulatory, inpatient, nrow = 1)


# california = outlier
cali <- dat_merge %>% 
  filter(Business_State_Territory == "California") %>% 
  summarize(total = n(), 
            amb = sum(Product_Setting == "Ambulatory"), 
            inpat = sum(Product_Setting == "Inpatient")) %>% 
  mutate("Ambulatory (Outpatient)" = amb/total, Inpatient = inpat/total) %>% 
  select("Ambulatory (Outpatient)", Inpatient)

prod_setting_overall <- bind_rows(prod_setting_overall,
                                  data_frame(State = "California",
                                             "Ambulatory (Outpatient)" = cali$`Ambulatory (Outpatient)`,
                                             Inpatient = cali$Inpatient
                                  ))
prod_setting_overall %>% kable
```


```{r}
sum(is.na(dat_merge$Vendor_Name))

top10 <- dat_merge %>% 
  filter(!is.na(Vendor_Name)) %>% 
  group_by(Vendor_Name) %>% 
  summarize(num = n()) %>% 
  arrange(desc(num)) %>% top_n(10)

vendors <- as.vector(top10$Vendor_Name)

dat_merge %>% filter(Vendor_Name %in% vendors) %>% 
  ggplot(aes(x = Vendor_Name)) + 
  geom_bar(aes(Vendor_Name)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

length(unique(factor(dat_merge$Vendor_Name)))

# percent usage of top 10
sum(top10$num)/nrow(dat_merge)

#dat_mu_ep %>% filter(n() > 5000) %>% ggplot() + geom_point(aes(x = Business_State_Territory, y = Vendor_Name, color = Vendor_Name))
#dat_mu_ep %>% group_by(Vendor_Name) %>% filter(n() < 5000) %>% ggplot() + geom_bar(aes(Vendor_Name))

pct_popvendors <- dat_merge %>% 
  group_by(Business_State_Territory) %>% 
  summarize(num = n(), 
            total_v = sum(Vendor_Name %in% vendors),
            opp = num - total_v) %>% 
  mutate(p_vend = total_v/num, u_vend = opp/num)

pct_popvendors %>% 
  ggplot() +
  geom_map(aes(map_id = id), data = fifty_states, map = fifty_states, color="grey50", fill="grey90") +
  geom_map(aes(map_id = tolower(Business_State_Territory), fill = p_vend), map = fifty_states, color="grey50") +
  coord_map() +
  scale_fill_gradientn(colors = brewer.pal(6, "RdYlGn")) +
  expand_limits(x=states_map$long, y=states_map$lat) +
  theme_gray() +
  theme(axis.text = element_blank(), 
        axis.line = element_blank(), 
        axis.ticks = element_blank(), 
        panel.border = element_blank(), 
        panel.grid = element_blank(), 
        axis.title = element_blank(),
        legend.position = "bottom") +
  ggtitle("Usage of Top 10 Vendors")

#do analysis within wisconsin, new york, tennessee
```

```{r}
#most common specialties in general
dat_merge %>% group_by(Primary.specialty) %>% summarize(num = n()) %>% arrange(desc(num))

# most common state -> specialty
specialty <- dat_merge %>% group_by(Business_State_Territory, Primary.specialty) %>% summarize(num = n()) %>% arrange(Business_State_Territory, desc(num))

#check similar specialties
dat_merge %>% filter(grepl("PSYCH", Primary.specialty)) %>% distinct(Primary.specialty)


specialty %>% ggplot(aes(Business_State_Territory, Primary.specialty)) +
  geom_tile(aes(fill = num))

specialty %>% ggplot(aes(x = Primary.specialty, y = num, fill = Business_State_Territory)) + geom_col()
```

```{r}
#load hosp data & clean
#hosp <- readRDS("~/Desktop/BST 260/BST-260-Final-Project/Hosp_merged_data.rds")
hosp$State.y[hosp$State.y == "ak_t"] <-"ak"
state_name <- c(state.name,"District Of Columbia")
states <- data.frame(state_name = state_name, state_abb = c(state.abb, "DC"))
hosp <- hosp %>% mutate(State.y = toupper(State.y)) %>% left_join(states, by = c("State.y" = "state_abb"))
```

```{r}
#take state pop into consideration?
beds <- hosp %>% 
  group_by(state_name) %>% 
  summarize(beds = mean(Staffed_beds)) 

beds %>% 
  ggplot() +
  geom_map(aes(map_id = id), data = fifty_states, map = fifty_states, color="grey50", fill="grey90") +
  geom_map(aes(map_id = tolower(state_name), fill = beds), map = fifty_states, color="grey50") +
  coord_map() +
  scale_fill_gradientn(colors = brewer.pal(6, "RdYlGn")) +
  expand_limits(x=states_map$long, y=states_map$lat) +
  theme_gray() +
  theme(axis.text = element_blank(), 
        axis.line = element_blank(), 
        axis.ticks = element_blank(), 
        panel.border = element_blank(), 
        panel.grid = element_blank(), 
        axis.title = element_blank(),
        legend.position = "bottom") +
  ggtitle("Hosp Beds")
```


```{r}
# patient days
hosp %>% 
  group_by(state_name) %>% 
  summarize(patient = mean(Patient_days)) %>% 
  ggplot() +
  geom_map(aes(map_id = id), data = fifty_states, map = fifty_states, color="grey50", fill="grey90") +
  geom_map(aes(map_id = tolower(state_name), fill = patient), map = fifty_states, color="grey50") +
  coord_map() +
  scale_fill_gradientn(colors = brewer.pal(6, "RdYlGn")) +
  expand_limits(x=states_map$long, y=states_map$lat) +
  theme_gray() +
  theme(axis.text = element_blank(), 
        axis.line = element_blank(), 
        axis.ticks = element_blank(), 
        panel.border = element_blank(), 
        panel.grid = element_blank(), 
        axis.title = element_blank(),
        legend.position = "bottom") +
  ggtitle("Across states, mean patient days per hospital on average")
```

```{r}
#total discharges
hosp %>% 
  group_by(state_name) %>% 
  summarize(discharges = mean(Total_discharges)) %>% 
  ggplot() +
  geom_map(aes(map_id = id), data = fifty_states, map = fifty_states, color="grey50", fill="grey90") +
  geom_map(aes(map_id = tolower(state_name), fill = discharges), map = fifty_states, color="grey50") +
  coord_map() +
  scale_fill_gradientn(colors = brewer.pal(6, "RdYlGn")) +
  expand_limits(x=states_map$long, y=states_map$lat) +
  theme_gray() +
  theme(axis.text = element_blank(), 
        axis.line = element_blank(), 
        axis.ticks = element_blank(), 
        panel.border = element_blank(), 
        panel.grid = element_blank(), 
        axis.title = element_blank(),
        legend.position = "bottom") +
  ggtitle("Across states, mean discharges days per hospital on average")
```

```{r}
#avg revenue per discharge

# need to fix - 0's in data
revenue <- hosp %>% 
  mutate(per = Gross_patient_revenue/Total_discharges)# %>% 
  # group_by(State.y) %>% 
  # summarize(rev = mean(per))

hosp %>% filter(Gross_patient_revenue==0)

revenue %>% 
  ggplot() +
  geom_map(aes(map_id = id), data = fifty_states, map = fifty_states, color="grey50", fill="grey90") +
  geom_map(aes(map_id = tolower(state_name), fill = rev), map = fifty_states, color="grey50") +
  coord_map() +
  scale_fill_gradientn(colors = brewer.pal(6, "RdYlGn")) +
  expand_limits(x=states_map$long, y=states_map$lat) +
  theme_gray() +
  theme(axis.text = element_blank(), 
        axis.line = element_blank(), 
        axis.ticks = element_blank(), 
        panel.border = element_blank(), 
        panel.grid = element_blank(), 
        axis.title = element_blank(),
        legend.position = "bottom") +
  ggtitle("Across states, average revenue per discharge")
```

size of hosp by state
specialty by state
income/top vendors
hospital density/size/region